baseurl = "/"
languageCode = "pt-br"
title = "P4H  - Material"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
relativeurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-119683862-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	# General information
	author = "P4H"
	description = "Material do Curso de Programação para Ciências Sociais"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/R4CS/site"

	version = ""
	logo = "logo_r4sc.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	github   = "p4hUSP"
	email    = "programacao.sociais@gmail.com"
	slack    = "p4husp"
	facebook = "p4hUSP"
	
[[menu.main]]
	name   = "Introdução"
	url    = "intro/"
	weight = 5
	
[[menu.main]]
	name   = "Gráficos"
	url    = "ggplot2/"
	weight = 10
	
[[menu.main]]
  name   = "Dplyr"
	url    = "dplyr/"
	weight = 13
	
[[menu.main]]
  name   = "Wrap Up"
	url    = "wrapup/"
	weight = 14
	
[[menu.main]]
	name   = "Mapas"
	url    = "mapas/"
	weight = 15
	
[[menu.main]]
	name   = "Web Scraping"
	url    = "webscraping/"
	weight = 20

[[menu.main]]
	name   = "Web Scraping - rvest"
	url    = "webscraping_rvest/"
	weight = 20
	
[[menu.main]]
 	name   = "SQL"
	url    = "sql/"
 	weight = 25
 	
[[menu.main]]
 	name   = "Text Mining"
	url    = "textmining/"
 	weight = 26
	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
